name: my_app
description: "NutriSense – Smart Nutrition & Wellness App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # ---------------- UI & ANIMATIONS ----------------
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # ---------------- DASHBOARD & CHARTS ----------------
  fl_chart: ^0.66.2
  percent_indicator: ^4.2.3

  # ---------------- CALENDAR & APPOINTMENTS ----------------
  table_calendar: ^3.1.2
  syncfusion_flutter_datepicker: ^27.2.5

  # ---------------- IMAGES & ASSETS ----------------
  cached_network_image: ^3.4.1

  # ---------------- STATE / UTILITIES ----------------
  intl: ^0.19.0
  fluttertoast: ^8.2.6

  # ---------------- SPLASH & APP ICON ----------------
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.14.4
  razorpay_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/eco-food-icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/eco-food-icon.png"
  windows:
    generate: true
    image_path: "assets/icons/eco-food-icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/eco-food-icon.png"
